### PR TITLE
Add Dockerfile

### PR DESCRIPTION
**Pull request by y0no**
Add a dockerfile to easily deploy matterllo as a container.
Moreover, this file allow to create an automated build on docker hub to get a fresh image at each push on this repository.

### CODE REVIEW

**Comment by Lujeni** [comment]
Hello @y0no 

Thanks for your nice contribution.

Imho, add the `unipath` library seems overkill. I prefer a documentation about the data dir directory and test the dir presence + error message.

Can you add a short documentation to show how to use this version (docker compose and co, where modified the trello api key ...)

Thanks again.

**Comment by y0no** [comment]
Yep ```unipath``` is certainly overkill in this file. I use it in most of my project so I take it by default. I will commit a version without it as soon as possible.

Concerning the documentation I will modify the README.md  to add a link to a documentation. Do you think it's interesting to add a docker-compose file ?

**Comment by y0no** [comment]
Here it is, tell me if this is good for you.

**Comment by Lujeni** [comment]
@y0no thanks for your work !

**Pull request merged**
